# Generated by Django 3.1.5 on 2021-01-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='date_ordered',
        ),
    ]
