# Generated by Django 3.1.5 on 2021-01-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_orden_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
