# Generated by Django 3.1.5 on 2021-01-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orden_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenproducto',
            old_name='orden',
            new_name='ordenacion',
        ),
    ]
