# Generated by Django 3.1.5 on 2021-01-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210129_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
