# Generated by Django 3.1.5 on 2021-01-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210129_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproducto',
            name='disponibles',
            field=models.IntegerField(blank=True, null=True, verbose_name=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.producto')),
        ),
    ]
