# Generated by Django 3.1.5 on 2021-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210130_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
