# Generated by Django 3.1.5 on 2021-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_producto_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='numero',
        ),
    ]
